name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    variables:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build Docker image
        run: docker build -t my-react-app:${IMAGE_TAG} .
      - name: Push Docker image to Docker Hub
        uses: docker/push-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: my-react-app
          image-tag: ${IMAGE_TAG}

